name: 飞书多维表格同步

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 6-22/2 * * *'  # 每天早上6点到晚上22点，每2小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/requirements.txt
          pip install requests
          
      - name: 准备工作目录
        run: |
          mkdir -p Python/{logs,output,dataBase}
          
      - name: 同步数据到飞书多维表格
        run: cd Python/src && python feishu_sync.py 1
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_BITABLE_ID: ${{ secrets.FEISHU_BITABLE_ID }}
          FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
          LARK_KEY: ${{ secrets.LARK_KEY }}  # 用于错误通知
          
      - name: 提交同步记录
        if: success()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Python/dataBase/feishu_sync_record.json || true
          git commit -m "更新飞书多维表格同步记录" || true
          git push || true 